# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
