# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_exp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='exp',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
