# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20170805_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exp',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='exp',
            old_name='date',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='field',
        ),
        migrations.AddField(
            model_name='exp',
            name='technology',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='exp',
            name='title',
            field=models.CharField(default=212, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exp',
            name='type',
            field=models.CharField(default=1212, max_length=100),
            preserve_default=False,
        ),
    ]
