# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20170805_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='favourite',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exp',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
