# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170806_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exp',
            name='favourite',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exp',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
