# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-06 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20170806_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='exp',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
