# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_exp_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exp',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='is_favourite',
        ),
        migrations.RemoveField(
            model_name='exp',
            name='likes',
        ),
    ]
