# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
