# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Bogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type', models.CharField(default='Social Blog', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Technology_Bogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('type', models.CharField(default='Technology Blog', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Work_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('Technology', models.CharField(max_length=100)),
                ('type', models.CharField(default='Work Log', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
