# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-05 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20170805_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology_Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=400)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('technology', models.CharField(max_length=100)),
                ('type', models.CharField(default='Technology Blog', max_length=1000)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Social_Bogs',
            new_name='Social_Blogs',
        ),
        migrations.DeleteModel(
            name='Technology_Bogs',
        ),
        migrations.RenameField(
            model_name='work_logs',
            old_name='Technology',
            new_name='technology',
        ),
    ]
