# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 21:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation_date')),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_date')),
                ('date_of_birth', models.DateTimeField(default=datetime.datetime(2017, 9, 23, 22, 30, 42, 966182), verbose_name='date_of_birth')),
                ('location', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
