# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 20:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 21, 48, 22, 328305), verbose_name='date_of_birth'),
        ),
    ]
