# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170924_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(verbose_name='date_of_birth'),
        ),
    ]
